# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 18:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidateManager', '0002_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='createdby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note',
            field=models.CharField(max_length=400),
        ),
    ]
